### PR TITLE
CAX-72-TM-typescript-refactor

### PR DESCRIPTION
**Pull request by alejandro-oyuela-vorihealth**

### CODE REVIEW

**Comment by alejandro-oyuela-vorihealth** [comment]
Please leave your thoughts on the organization of the directories to start doing the code splitting

**Comment by tonyebrown** [comment]
Here's how I'd break careplan.ts into separate files:

- **Root Directory
  - `index.ts`
    - Basically main entry point, imports all functions/etc. from sub-folders.
- **Folder: `init`**
  - `index.ts`
    - Contains functions for user interactions
      - `initAddButton`
      - `initBookAppointmentButton`
      - `rescheduleAppointment`
      - `verifyEmailPhone`
      - `verifyEmailPhoneButtons`
      - `waitAddAppointmentsBtn`
      - `waitAppointmentSidebar`
      - `waitAppointmentsHome`
      - `waitAppointmentsProfile`
      - `waitClientList`
      - `waitCarePlan`
      - `waitGoalTab`
      - `waitInfo`
      - `waitForAddPatientButton`
- **Folder: `api`**
  - `index.ts`
    - Contains API-related functions
      - `healthieGQL`
      - `isAPIconnected`

- **Folder: `utils`**
  - `index.ts`
    - Contains utility functions
      - `convertToCSSProperty`
      - `debugLog`
      - `waitForMishaMessages`

- **Folder: `helpers`**
  - Subfolder: `calendar`
    - `index.ts` // Contains calendar related helper functions
        - `initCalendar`
        - `initCalendarHeaderBtns`
        - `showBothCalendars`
        - `waitCalendar`
        - `initSidebarCalendar`
        - `setAppointmentCollapse`
  - Subfolder: `ui`
    - `index.ts` // Contains UI related helper functions
        - `addHoverEffect`
        - `removeHoverEffect`
        - `showOverlay`
        - `hideOverlay`
        - `createPatientDialogIframe`
        - `generateIframe`
        - `showInstructions`
  - `timeoutHelpers.ts` // Contains functions related to timeouts
      - `createTimeout`
      - `clearMyTimeout`

**Comment by tonyebrown** [comment]
Not sure I got all the functions, but this should work good
Feel free to rename folders to what makes sense
cc @alejandro-oyuela-vorihealth @dheatherington

**Comment by dheatherington** [comment]
@alejandro-oyuela-vorihealth Let's merge this when you come back from vacation next week and have a chance to make the changes from the repo that have happened since branch creation. We can make additional refactors but will be good to test all of the current changes

**Pull request closed without merging**
